### ISSUE TITLE
Does not handle Zone bridge

### ISSUE THREAD

**Issue by BillSobel** [rahims/SoCo#23] opened 2013-02-17 06:59 UTC
Currently the library causes a crash when it encounters a zone bridge.  The zone bridge only returns ZPSupportInfo but does not return ZPInfo.  So the code that assumes this is returned get_speaker_info throws an exception.

DEBUG:requests.packages.urllib3.connectionpool:"GET /status/zp HTTP/1.1" 200 None
<?xml version="1.0" ?>
<?xml-stylesheet type="text/xsl" href="/xml/review.xsl"?><ZPSupportInfo></ZPSupportInfo>
Traceback (most recent call last):
  File "./sonos.py", line 26, in <module>
    zone_name = device.get_speaker_info()['zone_name']
  File "/root/cps/shared/soco.py", line 648, in get_speaker_info
    self.speaker_info['zone_name'] = dom.findtext('.//ZoneName').encode('utf-8')
AttributeError: 'NoneType' object has no attribute 'encode'

**Comment by phut** [comment] 2013-02-17 11:30
how did you trigger this crash?  can be fixed directly in get_speaker_info however my guess is that the discovery routine should not be returning the bridge as part of the list of devices. were you particularly interested in addressing the bridge?

**Comment by BillSobel** [comment] 2013-02-17 17:31
Hi,

I wasn't trying to find the bridge, my code was just an initial test of the library and very basic.  I hacked up get_speaker_info() to return None for now (hence the test) and also had to catch ConnectionErrors as discovery is also finding my Philips Hue zigbee controller and then failing to connect 5 times after it does.

Cheers and thanks for the quick response.
Bill

if **name** == '**main**':
    logger = logging.getLogger( LOG_NAME )
    logger.setLevel(logging.INFO)

```
sonos_devices = SonosDiscovery()

for ip in sonos_devices.get_speaker_ips():
    device = SoCo(ip)

    try:
        if device.get_speaker_info() == None:
            continue
    except requests.exceptions.ConnectionError:
        continue

    zone_name = device.get_speaker_info()['zone_name']
    print "IP of %s is %s" % (zone_name, ip)        
```

**Comment by KennethNielsen** [comment] 2013-02-17 23:12
Hallo BillSobel

The fact that the discover is also finding non-zonos devices should probably be raised as a separate issue.

With regard to the problem with the bridge. Maybe the better way to solve this would be to make a communication and id check in the **init** method of SoCo. That would also allow us to handle it if people type in a wrong IP. Right now if you do that you will be allowed to instantiate the object, but it will then raise the same exception when you try to use one of the methods.

So what I would suggest is that from **init** method we call the same
requests.get('http://' + self.speaker_ip + ':1400/status/zp')
request as is used in the get_speaker_info method. If it raises an exception, we catch it and raise a custom "soco communications" exception of our own. If it returns none we raise another custom soco exception.

What do you think?

**Comment by BillSobel** [comment] 2013-02-17 23:25
I think you will also have to try and parse the response a bit in init since the bridge does respond, just not with the expected payload.

**Comment by KennethNielsen** [comment] 2013-02-18 23:22
Well yes and no. I read it wrong. It wasn't the request that returned None but the dom.find. But actually, I don't necessarily need to parse it, I just need to see that the normal parse fails. One way to do it would be to call the get_info method in **init** and parse the exceptions as described above. I have made an example implementation that it would be great of you would test out. You can get it by executing the following commands:

git clone https://github.com/KennethNielsen/SoCo.git
cd SoCo
git checkout check_for_bridge_and_invalid_ip

This should give you an informative exception the minute the try to instantiate, both in the case of your bridge and your Philips Hue zigbee. It should raise an ValueError in both cases, so you will only have to catch this one type of exception. We can of course discuss whether we should really make a custom exception for it in stead of using the value error.

I'm not sure this is the most elegant solution for the problem, but it may serve as a basis for discussion, so let me know what you think. Another possible solution for the problem is if we actually want soco to be able to interface the bridge, even though probably the only thing it can do is to give us some information about itself, then we can make more parsing code in get_speaker_info, still call it from **init** and then disable all other methods from **init** if we detect that it is a bridge.

**Comment by BillSobel** [comment] 2013-02-19 00:20
Ok tried the latest.  Throws the proper exception with the Hue controller so it is skipped.  It however is not throwing an exception for the Sonos Bridge (and as I am trying a second location as well, it also does not throw an exception for a Sonos Dock).

I think init may have to check to see if something like the uid is not None and then declare the device controllable (maybe have a Controllable property which is True for players but false for Bridges and Docks?).  Also FYI the Dock returns a fairly empty XML like the bridge.  The docks can be named so there must be a different call to get that (not that I think that is needed, just an FYI)

Dock raw return body:
<?xml version="1.0" ?>
<?xml-stylesheet type="text/xsl" href="/xml/review.xsl"?><ZPSupportInfo></ZPSupportInfo>

**Comment by KennethNielsen** [comment] 2013-02-19 08:30
That is my mistake. I somehow managed to not get the latest code down as a basis, which means that the .encode('utf-8') for the zone name, which gave the exception I'm listening for, is not present. I will fix it up tonight and send a new version.

**Comment by KennethNielsen** [comment] 2013-02-20 22:57
Ok. I have given it a new try. I have taken your advice and am now actually checking if we can parse the response for a uid. The reason I was a little reluctant to do it that way is, that I don't like copying code, but I think that you are right, that it is the better way to do it, so now I've implemented it. Would you care to test it for me. Same procedure as last time but with a different branch name:

git clone https://github.com/KennethNielsen/SoCo.git
cd SoCo
git checkout check_for_invalid_ip_and_non-controllable_sonos_device

I have added the checks both for the SoCo class and for the SoCoDiscovery class, since I think it is fair to assume that they should be able to produce correct results independently of each other. Please test both of them (provided you can remember or recreate with old code the "bad" IP's of you bridge and the zigbee for the SoCo test).

**Comment by DPH** [comment] 2013-03-01 14:49
Good spot. Have tested this on my set up and your code correctly excludes
the Bridge. Thank you.

Would change the text in the error message slightly to read:
'ValueError: Invalid IP address "192.168.1.95". The Sonos device specified
is not controllable.'
instead of:
'ValueError: Invalid IP address "192.168.1.95". The sonos device at the
specified is not controllable.'

Should then get it merged into the live version.

Regards David

**Comment by KennethNielsen** [comment] 2013-03-02 17:01
@DPH Thanks for testing it. It is good to know that it works with the bridge. BTW did you test the SonosDiscovery class as well? I'm hoping @BillSobel will test it as well before it is committed, to see if it also correctly excludes his zigbee.

Thanks for the hint on the exception string. I changed the formulation a few times and apparently ended of with two half formulations mixed together (embarrassing). I have fixed it in the branch.

**Comment by BillSobel** [comment] 2013-03-02 17:03
Sorry for the delay. Work had me in Spain last week now India. I should be
able to test this coming thurs/fri.

Cheers
Bill

Sent from my iPhone please excuse any typos.

On Mar 2, 2013, at 10:31 PM, Kenneth Nielsen notifications@github.com
wrote:

@DPH https://github.com/DPH Thanks for testing it. It is good to know
that it works with the bridge. BTW did you test the SonosDiscovery class as
well? I'm hoping @BillSobel https://github.com/BillSobel will test it as
well before it is committed, to see if it also correctly excludes his
zigbee.

Thanks for the hint on the exception string. I changed the formulation a
few times and apparently ended of with two half formulations mixed together
(embarrassing). I have fixed it in the branch.

—
Reply to this email directly or view it on
GitHubhttps://github.com/rahims/SoCo/issues/23#issuecomment-14331243
.

**Comment by DPH** [comment] 2013-03-02 22:18
Yes tested SonosDiscovery  class as well.
Used my son's bridge as I have my first Sonos unit connected directly
to Ethernet.

We also need to test with the new SonosSub, and the SonosTV sometime.

Great work,
Cheers David

**Comment by KennethNielsen** [comment] 2013-03-17 16:18
@BillSobel Hallo. Did you get a chance to test this?

**Comment by KennethNielsen** [comment] 2014-02-03 22:01
Development of SoCo contionues under https://github.com/SoCo

**Closed as completed by KennethNielsen** 2014-02-03 22:01 UTC
Labels: bug
